# site settings

title: Alejandro's landing page
description: A place to share my projects
taglong: a-silm landing page
tagshort: landing page
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/a-silm/a-silm.github.io

# author settings

author:
  name: a silm
  email: ale.sil.martz@gmail.com
photo: 

# social media links

social:
  github: a-silm
  linkedin: alejandrosilvam

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
